language: ruby
before_install: "gem install bundler"
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-19mode
notifications:
  email:
    - sheerun@sher.pl
